// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Stat struct {
	ID        pgtype.UUID
	UrlID     pgtype.UUID
	IpAddress pgtype.Text
	UserAgent pgtype.Text
	ClickedAt pgtype.Timestamp
}

type Url struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	OriginalUrl string
	ShortCode   string
	CreatedAt   pgtype.Timestamp
}

type User struct {
	ID        pgtype.UUID
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
}
