// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: url.sql

package db

import (
	"context"
)

const createShortURL = `-- name: CreateShortURL :one
INSERT INTO url(original_url,short_url) VALUES($1,$2) RETURNING id, original_url, short_url, created_at, updated_at, visits
`

type CreateShortURLParams struct {
	OriginalUrl string
	ShortUrl    string
}

func (q *Queries) CreateShortURL(ctx context.Context, arg CreateShortURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, createShortURL, arg.OriginalUrl, arg.ShortUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Visits,
	)
	return i, err
}

const getURLByShortURL = `-- name: GetURLByShortURL :one
SELECT id, original_url, short_url, created_at, updated_at, visits FROM url WHERE short_url = $1
`

func (q *Queries) GetURLByShortURL(ctx context.Context, shortUrl string) (Url, error) {
	row := q.db.QueryRow(ctx, getURLByShortURL, shortUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Visits,
	)
	return i, err
}
